### ISSUE TITLE
can't open large files

### ISSUE THREAD

**Issue by tobyatvibrant** [cthackers/adm-zip#129]
zipFile.js around line 14 says:

    if (inputType == Utils.Constants.FILE) {
        // is a filename
        filename = input;
        inBuffer = fs.readFileSync(filename); // <--- aaaargh!
        readMainHeader();

fs.readFileSync() tries to load the whole file into memory. My zip file is 32GB. Boom!

    buffer.js:72
        throw new RangeError('Attempt to allocate Buffer larger than maximum ' +
              ^
    RangeError: Attempt to allocate Buffer larger than maximum size: 0x3fffffff bytes
        at new Buffer (buffer.js:72:11)
        at Object.fs.readFileSync (fs.js:374:16)
        at new module.exports (C:\code\largefile\node_modules\adm-zip\zipFile.js:17:23)

My code is simply this:

    var AdmZip = require('adm-zip');
    var zip = new AdmZip("large_file.zip");

    zip.getEntries().forEach(function(zipEntry) {
        console.log(zipEntry.toString());
    });

Pretty sure you can read in the first few K of an archive and get the entries from that, rather than reading the whole file.

**Comment by focusaurus** [comment]
This is also preventing me from getting things installed.

**Comment by RickDT** [comment]
Same here. Any plans to open from a stream or something else that wouldn't try to load the entire file into memory?

**Comment by r03ert0** [comment]
Any news/workaround since June ?

**Comment by sayyedhanif** [comment]
I also not able to open the large zip file from this module.
is there any solution on that?

**Comment by tobydoig** [comment]
only took 11 years and 4 months, what's not to love?
