### ISSUE TITLE
ENOENT: no such file or directory, chmod '...'

### ISSUE THREAD

**Issue by kenny-evitt** [cthackers/adm-zip#162]
I'm trying to run `extractAllTo` in [Light Table](http://lighttable.com) to unzip a file to a directory. I'm getting the same error for both `true` or `false` for the `overwrite` parameter.

Light Table is ClojureScript running inside an Electron app. Here's the stack trace that Light Table throws:

```
Error: ENOENT: no such file or directory, chmod 'C:\@code\LightTable\builds\lighttable-0.8.1-windows\resources\app\tmp\lighttable-0.8.1-windows\resources\atom.asar'
    at Error (native)
    at Object.fs.chmodSync (fs.js:1012:18)
    at Object.module.exports.recoursive.writeFileTo (C:\@code\LightTable\builds\lighttable-0.8.1-windows\resources\app\core\node_modules\adm-zip\util\utils.js:108:20)
    at C:\@code\LightTable\builds\lighttable-0.8.1-windows\resources\app\core\node_modules\adm-zip\adm-zip.js:381:23
    at Array.forEach (native)
    at Object.module.exports.entry.extractAllTo (C:\@code\LightTable\builds\lighttable-0.8.1-windows\resources\app\core\node_modules\adm-zip\adm-zip.js:372:26)
    at unzip (C:\@code\LightTable\src\lt\objs\deploy.cljs[eval63]:138:97)
    at eval (C:\@code\LightTable\src\lt\objs\deploy.cljs[eval64]:143:22)
    at eval (native)
    at Function.<anonymous> (file:///C:/@code/LightTable/builds/lighttable-0.8.1-windows/resources/app/core/node_modules/lighttable/bootstrap.js:35242:461)
```

[This](https://github.com/LightTable/LightTable/releases/download/0.8.1/lighttable-0.8.1-windows.zip) is the file I'm attempting to extract. My code downloads it as *tmp.zip* and then is calling `zip.extractAllTo("C:\@code\LightTable\builds\lighttable-0.8.1-windows\resources\app\tmp", true)`.

Interestingly, most of the files were extracted. The files that were *not* extracted:

 - *lighttable-0.8.1-windows/*
   - *snapshot_blob.bin*
   - *ui_resources_200_percent.pak*
   - *vccorlib120.dll*
   - *xinput1_3.dll*
   - *resources/*
     - *atom.asar*
     - *default_app/*
       - *default_app.js*
       - *index.html*
       - *main.js*
       - *package.json*

**Comment by kenny-evitt** [comment]
I ran into a very suspiciously similar error using another zip library:

 - [antelle/node-stream-zip: node.js library for fast reading of large ZIPs](https://github.com/antelle/node-stream-zip)

I now suspect that the problem is [Electron patching filesystem functions](https://github.com/atom/electron/issues/1658).

**Comment by thomas-void0** [comment]
I have the same question.as your said, fs of electron module is specific. It be differ from fs of node module.so fs of electron can read asar file. fs of node module will throw error.

can resolved this question by set `process.noAsar = true` in your front of adm-zip function
