### ISSUE TITLE
RangeError: index out of range

### ISSUE THREAD

**Issue by ReDreamport** [cthackers/adm-zip#164]
Hi, I got a RangeError with following stack:

```
RangeError: index out of range
    at checkOffset (buffer.js:635:11)
    at Buffer.readUInt16LE (buffer.js:681:5)
    at parseExtra (/Users/maximus/dev/codes/wpax/FastContentProvider/extension/node_modules/node-apk-parser/node_modules/adm-zip/zipEntry.js:154:25)
    at Object.extra (/Users/maximus/dev/codes/wpax/FastContentProvider/extension/node_modules/node-apk-parser/node_modules/adm-zip/zipEntry.js:209:13)
    at readEntries (/Users/maximus/dev/codes/wpax/FastContentProvider/extension/node_modules/node-apk-parser/node_modules/adm-zip/zipFile.js:40:29)
    at readMainHeader (/Users/maximus/dev/codes/wpax/FastContentProvider/extension/node_modules/node-apk-parser/node_modules/adm-zip/zipFile.js:72:9)
    at new module.exports (/Users/maximus/dev/codes/wpax/FastContentProvider/extension/node_modules/node-apk-parser/node_modules/adm-zip/zipFile.js:18:9)
    at new module.exports (/Users/maximus/dev/codes/wpax/FastContentProvider/extension/node_modules/node-apk-parser/node_modules/adm-zip/adm-zip.js:17:20)
    at new ApkReader (/Users/maximus/dev/codes/wpax/FastContentProvider/extension/node_modules/node-apk-parser/lib/apkreader.js:23:20)
    at Function.ApkReader.readFile (/Users/maximus/dev/codes/wpax/FastContentProvider/extension/node_modules/node-apk-parser/lib/apkreader.js:16:14)
```

**Comment by weiyin** [comment]
I am encountering the same issue with version 0.4.7. It worked fine in version 0.4.4.

**Comment by kocuroglu** [comment]
Same here, trying to unzip 43 MB file.

Also 0.4.6 is not compatible with node v4

```
Unhandled rejection RangeError: index out of range
    at checkOffset (buffer.js:506:11)
    at Buffer.readUInt16LE (buffer.js:552:5)
    at parseExtra (/home/bor/code/mdm-server/node_modules/adm-zip/zipEntry.js:152:30)
    at Object.extra (/home/bor/code/mdm-server/node_modules/adm-zip/zipEntry.js:209:13)
    at readEntries (/home/bor/code/mdm-server/node_modules/adm-zip/zipFile.js:40:29)
    at readMainHeader (/home/bor/code/mdm-server/node_modules/adm-zip/zipFile.js:72:9)
    at new module.exports (/home/bor/code/mdm-server/node_modules/adm-zip/zipFile.js:18:9)
    at new module.exports (/home/bor/code/mdm-server/node_modules/adm-zip/adm-zip.js:17:20)
```

I can attach the file if needed (some version of google play services apk)

**Comment by id0Sch** [comment]
im having the same problem as @kocuroglu , exactly the same usage
