### ISSUE TITLE
Cannot unzip large file (more than 2.

### ISSUE THREAD

**Issue by angryhorse0905** [cthackers/adm-zip#190]

**Comment by angryhorse0905** [comment]
This is the code what I test.
`var AdmZip = require('adm-zip');

var zippath = "/Volumes/DEV/Projects/TalkEnglish_Material/Packages/production/vocab.zip";
console.info("ZIPPATH:", zippath);

// reading archives
var zip = new AdmZip(zippath);
var zipEntries = zip.getEntries();
`
the file size is actually 2.6GB and it shows me the following error.
`RangeError: Invalid typed array length
    at Buffer.Uint8Array (native)
    at FastBuffer (buffer.js:11:5)
    at createUnsafeBuffer (buffer.js:38:12)
    at allocate (buffer.js:181:12)
    at Function.Buffer.allocUnsafe (buffer.js:141:10)
    at tryCreateBuffer (fs.js:474:21)
    at Object.fs.readFileSync (fs.js:519:14)
    at new module.exports (/Users/dev/Downloads/testzip/node_modules/adm-zip/zipFile.js:17:23)
    at new module.exports (/Users/dev/Downloads/testzip/node_modules/adm-zip/adm-zip.js:17:20)
    at Object.<anonymous> (/Users/dev/Downloads/testzip/test.js:7:11)
`
Please let me know how to extract large file using adm-zip library
