### ISSUE TITLE
Issue with v0.4.11 extractEntryTo method, maintainEntryPath arg usage

### ISSUE THREAD

**Issue by sivamgr** [cthackers/adm-zip#237]
While testing v0.4.11, when a folder path is passed to extractEntryTo method, files gets extracted into incorrect folder. 
if "/tmp" is passed as mainEntryPath.. the files gets extracted into "/tmp/tmp" folder.

It was working fine with v0.4.7

**Comment by dogancelik** [comment]
**version 0.4.9 is working**

This new version (0.4.11) duplicates extraction path: `D:\Portable\FileZilla\D:\Portable\FileZilla\` as you can see from the error log below:

```
CWD = C:\Users\dogan\AppData\Local\Temp
$ endl dx "https://filezilla-project.org/download.php?show_all=1" "[href*='win64.zip']" "--cdr=FileZilla" --to "D:\Portable\FileZilla"
Download URL: https://dl1.cdn.filezilla-project.org/client/FileZilla_3.33.0_win64.zip
File is saved to: C:\Users\dogan\AppData\Local\Temp\FileZilla_3.33.0_win64.zip

# fromPath = entry.entryName = 'FileZilla-3.33.0/filezilla.exe'
# toPath = 'D:\Portable\FileZilla'

fs.js:1123
  return binding.chmod(pathModule._makeLong(path), modeNum(mode));
                 ^

Error: ENOENT: no such file or directory, chmod 'D:\Portable\FileZilla\D:\Portable\FileZilla\filezilla.exe'
  at Object.fs.chmodSync (fs.js:1123:18)
  at Object.writeFileTo (D:\Projects\Public\endl\node_modules\adm-zip\util\utils.js:111:20)
  at Object.extractEntryTo (D:\Projects\Public\endl\node_modules\adm-zip\adm-zip.js:385:10)
  at D:\Projects\Public\endl\lib\file.js:247:20
  at Array.forEach (<anonymous>:null:null)
  at File._extractOnFinish (D:\Projects\Public\endl\lib\file.js:227:13)
  at Object.onceWrapper (events.js:313:30)
  at emitNone (events.js:106:13)
  at EventEmitter.emit (events.js:208:7)
  at WriteStream.<anonymous> (D:\Projects\Public\endl\lib\file.js:161:32)
  at emitNone (events.js:111:20)
  at WriteStream.emit (events.js:208:7)
  at finishMaybe (_stream_writable.js:614:14)
  at afterWrite (_stream_writable.js:465:3)
  at onwrite (_stream_writable.js:455:7)
  at fs.write (fs.js:2192:5)
  at FSReqWrap.wrapper [as oncomplete] (fs.js:685:5)
```

**Comment by apexearth** [comment]
Yeah this totally bonked my application too.

**Comment by apexearth** [comment]
Created PR #238 to fix this..

**Comment by Twizzeld** [comment]
I tried manually applying the fix in PR # 238 and I'm still getting the following error.
`Error: ENOENT: no such file or directory, chmod 'C:\Users\Ryan\Desktop\adm-zip-test\C:\Users\Ryan\Desktop\adm-zip-test\test.txt'`

As you can see it's doubling the targetPath. 

I did a little digging and it looks like it's being cause by the sanitize function in adm-zip.js ... line 30. I'm not sure I fully understand what's going on in this function. But it looks like line 33 `var path = pth.normalize(pth.join(prefix, parts.slice(i, l).join(pth.sep)));` is what's creating the double path. 

Anyways, when I change line 365 to `var target = entryName` everything works as expected.

 I've copied my zip, code and full error message below. Let me know what you guys think.

Thanks.

Node: v6.13.1
Windows 10

update.zip ->
- lib (folder)
  - advanced_desktop (folder)
    - text.txt
  - basic_desktop (folder)
    - text.txt


index.js ->
var admZip = require("adm-zip");
var zip = new admZip("./update.zip");
var zipEntries = zip.getEntries();

zipEntries.forEach(function(zipEntry) {
	if (!zipEntry.isDirectory) {
		zip.extractEntryTo(zipEntry, './', false, true);
	}
});

ERROR ->
Error: ENOENT: no such file or directory, chmod 'C:\Users\Ryan\Desktop\adm-zip-test\C:\Users\Ryan\Desktop\adm-zip-test\test.txt'
    at Error (native)
    at Object.fs.chmodSync (fs.js:1177:18)
    at Object.writeFileTo (C:\Users\Ryan\Desktop\adm-zip-test\node_modules\adm-zip\util\utils.js:111:20)
    at Object.extractEntryTo (C:\Users\Ryan\Desktop\adm-zip-test\node_modules\adm-zip\adm-zip.js:385:19)
    at C:\Users\Ryan\Desktop\adm-zip-test\index.js:8:7
    at Array.forEach (native)
    at Object.<anonymous> (C:\Users\Ryan\Desktop\adm-zip-test\index.js:6:12)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)

**Comment by apexearth** [comment]
I've added commit bdc6eaccc90442c2049ec7445202e0087880316d to test your case and I wasn't able to replicate your issue.

Can you try cloning this repository and running the tests yourself to verify they all pass on your machine?

```
git clone https://github.com/cthackers/adm-zip.git
cd adm-zip
npm install
npm test
```

**Comment by Twizzeld** [comment]
I ran the tests from your fork and they all passed.

I was experiencing some other issues and decided to reinstall node. After that my original example appears to be working now.

Appears the problems were all on my end. Sorry, my bad guys.

Keep up the good work.

**Comment by cvaughn55** [comment]
Is there a way to get this fix? i installed the module through npm and still have the issue

**Comment by apexearth** [comment]
@cvaughn55, If he hasn't published the merge yet then you can npm install this repository directly from the git URL.
