### ISSUE TITLE
Broken  binding.writeBuffer on adm-zip@0.4.13

### ISSUE THREAD

**Issue by tormozz48** [cthackers/adm-zip#265]
```js
fs.js:720
    return binding.writeBuffer(fd, buffer, offset, length, position, req);
                   ^

TypeError: First argument must be file descriptor
    at Object.fs.write (fs.js:720:20)
    at /Users/andrey/Work/cdn-sync/node_modules/adm-zip/util/utils.js:153:44
    at FSReqWrap.oncomplete (fs.js:149:20)
```

Works fine on 0.4.11

**Comment by farhantariq92** [comment]
I am using 0.4.14 and facing same problem.

`TypeError: First argument must be file descriptor
    at Object.fs.write (fs.js:702:20)
    at /usr/local/appsight-server-api/node_modules/adm-zip/util/utils.js:153:44
    at FSReqWrap.oncomplete (fs.js:135:15)
internal/process.js:103
    memoryUsage_(memValues);
    ^
Error: EMFILE: too many open files, uv_resident_set_memory
    at process.memoryUsage (internal/process.js:103:5)`
