### ISSUE TITLE
RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. It must be >= 0 and <= 4294967295

### ISSUE THREAD

**Issue by at4446** [cthackers/adm-zip#375]
I have a large file to zip but get this error. Any idea how to resolve this? 
`
RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. It must be >= 0 and <= 4294967295. Received -262042185
    at checkInt (internal/buffer.js:68:11)
    at writeU_Int32LE (internal/buffer.js:688:3)
    at Buffer.writeUInt32LE (internal/buffer.js:701:10)
    at Object.dataHeaderToBinary `

**Comment by Vollikene** [comment]
It seems like -262042185 is position where Read/Write tries to access.

**Comment by at4446** [comment]
@Vollikene thank you for your comment. I am not sure what you exactly mean? how to resolve it? I think it is memory allocation issue.

**Comment by 5saviahv** [comment]
@at4446  Can you provide more information. I understand you tried read a ZIP file and it gave you this error. Sadly error text alone wont help find a problem. It tells us adm-zip tried a read data from negative location of a file and it seems not logical. What version you used ? Can you provide stack trace, so we can see where it happens ?

@Vollikene Yes, it seems like negative location and it seems not logical.

**Comment by Vollikene** [comment]
Actually it seems like function `dataHeaderToBinary` tries write UInt32LE value, but it is negative. There are 4 UInt32 values there:
- time
- crc
- size 
- compressed size.

**Comment by danilo900** [comment]
Hello, Iam trying to Zip a large folder (500mb, 8 thousand files).

And after using zip.addLocalFolder nothing happens and my process ends.

Using version 0.5.5

**Comment by acidjazz** [comment]
is there no solution to this or workaround? I get this a lot with github actions on folders > 500MB  @5saviahv @cthackers

**Comment by acidjazz** [comment]
This is my specific error
```
[FAILED] The value of "value" is out of range. It must be >= 0 and <= 65535. Received 68355

[FAILED] The value of "value" is out of range. It must be >= 0 and <= 65535. Received 68355

```

**Comment by 5saviahv** [comment]
> The value of "value" is out of range. It must be >= 0 and <= 65535. Received 68355

... Is error from node Buffer and is most likely caused by count of files.

This 65535 file limit is caused because currently adm-zip can read from zip64 extended files but is not able to write them.

**Comment by acidjazz** [comment]
> > The value of "value" is out of range. It must be >= 0 and <= 65535. Received 68355
> 
> ... Is error from node Buffer and is most likely caused by count of files.
> 
> This 65535 file limit is caused because currently adm-zip can read from zip64 extended files but is not able to write them.

So is there any kind fo solution or bypass for this?

**Comment by FredericHeem** [comment]
Same problem here with a 20MB folder.

**Comment by ubiscope-dev** [comment]
Hi,
The last post on this thread is a year old. Has anything evolved since then? I am getting the same message zipping a large folder. It is a bit of a problem. Zipping small files is super but the unfortunate fact is that you usually want to zip large files. Try figure!

**Comment by FredericHeem** [comment]
I have a non mergeable fix at https://github.com/FredericHeem/adm-zip/tree/time_ERR_OUT_OF_RANGE
The idea is to set to time field to 0, needed to make the zip predictable, i.e same input => same output.
