### ISSUE TITLE
Error while extracting to a path containing colon

### ISSUE THREAD

**Issue by AvrahamO** [cthackers/adm-zip#409]
When one of the folders in path contains a colon, the method `extractAllTo` throws
```bash
Error: ENOENT: no such file or directory, chmod '/usr/app/path:colon/zipfile/file.json'
    at Object.chmodSync (node:fs:1826:3)
    at Utils.writeFileTo (/usr/app/node_modules/adm-zip/util/utils.js:83:17)
    at /usr/app/node_modules/adm-zip/adm-zip.js:616:27
    at Array.forEach (<anonymous>)
    at Object.extractAllTo (/usr/app/node_modules/adm-zip/adm-zip.js:604:26)
    at [eval]:1:60
    at Script.runInThisContext (node:vm:129:12)
    at Object.runInThisContext (node:vm:305:38)
    at node:internal/process/execution:81:19
    at [eval]-wrapper:6:22 {
  errno: -2,
  syscall: 'chmod',
  code: 'ENOENT',
  path: '/usr/app/path:colon/zipfile/file.json'
}
```

After digging in the code, I saw the [following line](https://github.com/cthackers/adm-zip/blob/bebbabf600a6ae5d64ee31cbc89a1274bd1d8c1f/util/utils.js#L45):
```js
            if (!name || name.substr(-1, 1) === ":") return;
```

What is the reason for this code?

**Comment by 5saviahv** [comment]
> What is the reason for this code?

I believe it should remove "drive letters" under windows. But it needs some further investigation.
