### ISSUE TITLE
Symlinks are not supported?

### ISSUE THREAD

**Issue by DenisBY** [cthackers/adm-zip#456]
I'm getting an error:

```
Exiting with error Error: ENOENT: no such file or directory, stat '/tmp/kabuki/kabuki-core/dlls/libd3dcompiler.def'
    at Object.statSync (fs.js:1132:3)
    at /var/task/node_modules/adm-zip/util/utils.js:158:25
    at Array.forEach (<anonymous>)
    at findSync (/var/task/node_modules/adm-zip/util/utils.js:155:34)
    at /var/task/node_modules/adm-zip/util/utils.js:158:89
    at Array.forEach (<anonymous>)
    at findSync (/var/task/node_modules/adm-zip/util/utils.js:155:34)
    at /var/task/node_modules/adm-zip/util/utils.js:158:89
    at Array.forEach (<anonymous>)
    at findSync (/var/task/node_modules/adm-zip/util/utils.js:155:34) {
  errno: -2,
  syscall: 'stat',
  code: 'ENOENT',
  path: '/tmp/kabuki/kabuki-core/dlls/libd3dcompiler.def'
}
```

where `libd3dcompiler.def` is, at the moment, a broken link to `d3dcompiler_43/libd3dcompiler.def`

**Comment by 5saviahv** [comment]
no, not yet. but I plan to add it #455
