### ISSUE TITLE
Error: invalid stored block lengths. Library can't extract archive after your today's release

### ISSUE THREAD

**Issue by agubskyy** [cthackers/adm-zip#473]
Error: invalid stored block lengths
    at Zlib.zlibOnError [as onerror] (zlib.js:187:17)
    at processChunkSync (zlib.js:451:12)
    at zlibBufferSync (zlib.js:175:12)
    at Object.syncBufferWrapper [as inflateRawSync] (zlib.js:786:14)
    at Object.inflate (node_modules/adm-zip/methods/inflater.js:6:25)
    at decompress node_modules/adm-zip/zipEntry.js:80:45)
    at Object.getData (node_modules/adm-zip/zipEntry.js:268:24)
    at eval (webpack://library/./routes/connectors.js?:1289:53)
    at Layer.handle [as handle_request] (node_modules/express/lib/router/layer.js:95:5)
    at next (node_modules/express/lib/router/route.js:149:13)
    
 I can't unpack any of my production zip archives after npm install

**Comment by agubskyy** [comment]
Previous versions are not working too after your v0.5.11 update!

**Comment by agubskyy** [comment]
Production errors:

 [ERROR] [Worker Running Error] Error: invalid stored block lengths
    at Zlib.zlibOnError [as onerror] (zlib.js:187:17)
    at processChunkSync (zlib.js:451:12)
    at zlibBufferSync (zlib.js:175:12)
    at Object.syncBufferWrapper [as inflateRawSync] (zlib.js:786:14)
    at Object.inflate (/app/packages/node_modules/adm-zip/methods/inflater.js:6:25)
    at decompress (/app/packages/node_modules/adm-zip/zipEntry.js:80:45)
    at Object.getData (/app/packages/node_modules/adm-zip/zipEntry.js:268:24)
    at /app/packages/node_modules/adm-zip/adm-zip.js:612:37
    at Array.forEach (<anonymous>)
    at Object.extractAllTo (/app/packages/node_modules/adm-zip/adm-zip.js:606:26) {
  errno: -3,
  code: 'Z_DATA_ERROR'
}

**Comment by Aperion** [comment]
We got hit with this error as well. The strange thing is only one zip out of 8 had this error, and the same zip worked in previous version of adm-zip

**Comment by sronsiek** [comment]
Same here! In my case `adm-zip` is a dependency of another package which required `"^0.5.0"`.
This is pulling 0.5.11 from npm ...

Fortunately I  was able to pin 0.5.10 in my package.json using a `"resolution"` clause.

**Comment by lukemalcolm** [comment]
I've tracked this issue down to this pull request #451 

I'd suggest this pull request is reverted @cthackers.
