### ISSUE TITLE
extractAllTo is broken with 0.5.15

### ISSUE THREAD

**Issue by chandanjainn** [cthackers/adm-zip#533]
Got the following error with v0.5.15. It was working until 0.5.14

`Error: ADM-ZIP: Descriptor data is malformed
    at Object.DESCRIPTOR_FAULTY (/usr/src/app/node_modules/adm-zip/util/errors.js:56:16)
    at crc32OK (/usr/src/app/node_modules/adm-zip/zipEntry.js:62:36)
    at decompress (/usr/src/app/node_modules/adm-zip/zipEntry.js:121:26)
    at Object.getData (/usr/src/app/node_modules/adm-zip/zipEntry.js:320:24)
    at /usr/src/app/node_modules/adm-zip/adm-zip.js:762:37
    at Array.forEach (<anonymous>)
    at Object.extractAllTo (/usr/src/app/node_modules/adm-zip/adm-zip.js:756:26)
    at download_and_unzip (/usr/src/app/processes/utils/batch.utils.js:64:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async module.exports.getProcessedFile (/usr/src/app/processes/utils/batch.utils.js:79:37)`

The following data integrity check seems to be failing 
![image](https://github.com/user-attachments/assets/89aa46eb-8fe6-4cdb-a028-a4abcad12453)

**Comment by devland** [comment]
The weird thing is that this happens only on some systems.
For me it does not happen but for a colleague of mine it does and we're both running the same amd-zip powered code with the same adm-zip version.
So there may also be a race condition or some other aspect involved that makes the same zip file fail the check on one system while it always passes on another.

**Comment by devland** [comment]
As of v0.5.16 we can no longer reproduce the problem.

**Comment by devland** [comment]
We managed to reproduce this again on v0.5.16 and on master branch as of writing this (https://github.com/cthackers/adm-zip/commit/1cd32f7e0ad3c540142a76609bb538a5cda2292f).

To reproduce locally run `extractAllTo` on the below attached zip file.

[descriptorMalformed.zip](https://github.com/user-attachments/files/18887751/descriptorMalformed.zip)

**Comment by sdg9670f** [comment]
I think validating descriptors should be optional.

**Comment by cthackers** [comment]
Fixed
