### ISSUE TITLE
Regression between 0.5.14 and 0.5.15 in decompressing some valid ZIP archives

### ISSUE THREAD

**Issue by hannesj** [cthackers/adm-zip#548]
Seems like this is caused by https://github.com/cthackers/adm-zip/pull/508. I've attached a file which according to `unzip` is valid, while adm-zip starts throwing when decompressing it starting from version 0.5.14 with the following error message:

```
     Error: ADM-ZIP: No descriptor present
      at Object.DESCRIPTOR_NOT_EXIST (util/errors.js:56:16)
      at crc32OK (zipEntry.js:42:36)
      at decompress (zipEntry.js:121:26)
      at Object.getData (zipEntry.js:320:24)
      at Context.<anonymous> (test/issue_533.test.js:21:37)
      at process.processImmediate (node:internal/timers:483:21)
```

[testfile.zip](https://github.com/user-attachments/files/18198695/testfile.zip)

**Comment by bcerquiare** [comment]
Same problem here

**Comment by alanwilter** [comment]
Are you guys still experiencing this issues with v.0.5.16?

**Comment by zfyzjzzl** [comment]
> Are you guys still experiencing this issues with v.0.5.16?

Yes I'm still facing and do not know why

**Comment by cthackers** [comment]
Fixed
