### ISSUE TITLE
Error while adding files to zip

### ISSUE THREAD

**Issue by nukulb** [cthackers/adm-zip#92]
My code is quite simple

zip = new AdmZip('myZip.zip');
zip.addLocalFile('myFile.jpeg');
zip.writeZip();

And that throws the following error. Not sure if I doing something wrong but it seems straight forward.
Any help would be appreciated.

```
buffer.js:582
    throw new RangeError('Trying to access beyond buffer length');
    ^
RangeError: Trying to access beyond buffer length
    at checkOffset (buffer.js:582:11)
    at Buffer.readUInt32LE (buffer.js:642:5)
    at Object.loadDataHeaderFromBinary (/Users/nukulb/src/hubba-node/node_modules/adm-zip/headers/entryHeader.js:112:22)
    at getCompressedDataFromZip (/Users/nukulb/src/hubba-node/node_modules/adm-zip/zipEntry.js:19:22)
    at compress (/Users/nukulb/src/hubba-node/node_modules/adm-zip/zipEntry.js:94:20)
    at Object.getCompressedData (/Users/nukulb/src/hubba-node/node_modules/adm-zip/zipEntry.js:165:20)
    at /Users/nukulb/src/hubba-node/node_modules/adm-zip/zipFile.js:186:44
    at Array.forEach (native)
    at Object.compressToBuffer (/Users/nukulb/src/hubba-node/node_modules/adm-zip/zipFile.js:182:23)
    at Object.writeZip (/Users/nukulb/src/hubba-node/node_modules/adm-zip/adm-zip.js:384:32)
    at /Users/nukulb/src/hubba-node/lib/controllers/downloadProducts.js:245:17
```

**Comment by rtm** [comment]
I have the some error, although in my case it happens when calling `toBuffer`. It appears to be related to binary files--at least, png and jpg fail, and html and css do not. The same error occurs when I read the file in myself and use `addFile` to add it. Any ideas or workarounds for this?
